### ISSUE TITLE
[Windows 7] render-to-file would cause the involved template file not being released causing subsequent modification and save to it getting violation error

### ISSUE THREAD

**Issue by yubrshen** [tomfaulhaber/excel-templates#20] opened 2015-10-27 00:05 UTC
On my Windows 7 with emacs 24.5 cider 0.10
once having executed render-to-file from cider repl, modification to the template excel file would not be able to save to itself, with "sharing violation" error. 

Checking with Process Explorer, I confirmed that the one of the two Java processes started from emacs/cider hold two handles to the template file. Manually release the two handles, would solve the problem.

Would calling garbage collection at the end of render-to-file solve the problem?

**Comment by yubrshen** [comment] 2015-10-28 22:08
From the help information from Excel 2015, it seems that the problem might be related to the anti-virus program;

```
When saving a file, a sharing violation can be caused by the way an antivirus application interacts with Microsoft Office.
Check with your antivirus provider to make sure that the current version of the application, including updates, is installed. The antivirus provider might also have information or solutions for sharing violation issues.
```

**Comment by yubrshen** [comment] 2015-10-28 22:39
I confirm that the problem is with the Java process for the JVM for render-to-file.

**Comment by tomfaulhaber** [comment] 2016-02-20 02:05
Duplicate of issue #23

**Closed** 2016-02-20 02:07 UTC
